In [1]:
#Линейные модели, SVM и деревья решений.

import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline 
sns.set(style="ticks")

In [2]:
data = pd.read_csv('../../ML_datasets/heart.csv')
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
data.shape

(303, 14)

In [63]:
#3. С использованием метода train_test_split разделите выборку на обучающую и тестовую.
x_train, x_test, y_train, y_test = train_test_split(
    data.loc[:, data.columns != 'target'], data['target'],
    test_size=0.3, random_state=1)

In [64]:
#Обучающая выборка
x_train.shape, y_train.shape

((212, 13), (212,))

In [65]:
#Тестовая выборка
x_test.shape, y_test.shape

((91, 13), (91,))

In [66]:
#4.1. Обучаем одну из линейных моделей, делаем предикт, оцениваем качество моделей с помощью трех подходящих для задачи метрик.
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score

sgd = SGDClassifier().fit(x_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [67]:
target_sgd = sgd.predict(x_test)

In [68]:
accuracy_score(y_test, target_sgd), precision_score(y_test, target_sgd),recall_score(y_test, target_sgd)

(0.6813186813186813, 0.7058823529411765, 0.72)

In [69]:
#4.2. Обучаем SVM, делаем предикт, оцениваем качество моделей с помощью трех подходящих для задачи метрик.
from sklearn.svm import SVC

svm = SVC(gamma='auto')
svm.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [70]:
target_svm = svm.predict(x_test)

In [71]:
accuracy_score(y_test, target_svm), precision_score(y_test, target_svm),recall_score(y_test, target_svm)

(0.5604395604395604, 0.5555555555555556, 1.0)

In [72]:
#4.3. Обучаем дерево решений, делаем предикт, оцениваем качество моделей с помощью трех подходящих для задачи метрик.
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=1, max_depth=0.75).fit(x_train, y_train)
target_decision_tree = decision_tree.predict(x_test)

In [73]:
accuracy_score(y_test, target_decision_tree), precision_score(y_test, target_decision_tree), recall_score(y_test, target_decision_tree)

(0.5494505494505495, 0.5494505494505495, 1.0)

In [74]:
#5.Произведите для каждой модели подбор одного гиперпараметра с использованием GridSearchCV и кросс-валидации.
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

scores_sgd = cross_val_score(SGDClassifier(), 
                         x_train, y_train, cv=2)
scores_sgd

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


array([0.57943925, 0.7047619 ])

In [75]:
scores_svm = cross_val_score(SVC(gamma='auto'), 
                         x_train, y_train, cv=3)
scores_svm

array([0.54166667, 0.54285714, 0.54285714])

In [76]:
scores_decision_tree = cross_val_score(DecisionTreeClassifier(), 
                         x_train, y_train, cv=3)
scores_decision_tree

array([0.86111111, 0.78571429, 0.81428571])

In [77]:
parameters = {'alpha':[0.7,0.6,0.5,0.4,0.3,0.2,0.1]}
clf_gs_sgd = GridSearchCV(SGDClassifier(), parameters, cv=3, scoring='accuracy')
clf_gs_sgd.fit(x_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=None,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'alpha': [0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [78]:
clf_gs_sgd.best_params_

{'alpha': 0.2}

In [79]:
parameters = {'gamma':[0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1]}
clf_gs_svm = GridSearchCV(SVC(), parameters, cv=2, scoring='accuracy')
clf_gs_svm.fit(x_train, y_train)

GridSearchCV(cv=2, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'gamma': [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [80]:
clf_gs_svm.best_params_

{'gamma': 0.9}

In [81]:
parameters = {'min_impurity_decrease':[0.9,0.8,0.7,0.6,0.5,0.4,0.3,0.2,0.1]}
clf_gs_decision_tree = GridSearchCV(DecisionTreeClassifier(), parameters, cv=2, scoring='accuracy')
clf_gs_decision_tree.fit(x_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=2, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'min_impurity_decrease': [0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [82]:
clf_gs_decision_tree.best_params_

{'min_impurity_decrease': 0.1}

In [83]:
#6.Повторите пункт 4 для найденных оптимальных значений гиперпараметров.
#Сравните качество полученных моделей с качеством моделей, полученных в пункте 4.

#Обучаем одну из линейных моделей
sgd_best = SGDClassifier(alpha=0.2).fit(x_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


In [84]:
target_sgd_best = sgd_best.predict(x_test)

In [85]:
accuracy_score(y_test, target_sgd_best), precision_score(y_test, target_sgd_best),recall_score(y_test, target_sgd_best)

(0.6043956043956044, 0.5813953488372093, 1.0)

In [86]:
#Обучаем SVM
svm_best = SVC(gamma=0.9)
svm_best.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.9, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [87]:
target_svm_best = svm_best.predict(x_test)

In [88]:
accuracy_score(y_test, target_svm_best),precision_score(y_test, target_svm_best), recall_score(y_test, target_svm_best)

(0.5494505494505495, 0.5494505494505495, 1.0)

In [89]:
#Обучаем дерево решений
best_decision_tree = DecisionTreeClassifier(random_state=1,
                                            max_depth=0.75,
                                            min_impurity_decrease=0.1).fit(x_train,
                                                                           y_train)

In [90]:
best_target_decision_tree = best_decision_tree.predict(x_test)

In [91]:
accuracy_score(y_test, best_target_decision_tree),precision_score(y_test, best_target_decision_tree),recall_score(y_test, best_target_decision_tree)

(0.5494505494505495, 0.5494505494505495, 1.0)